name: flutter_page_curl_example
description: Example app for flutter_page_curl package

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_page_curl:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
